import { gsspWithNonce } from '@next-safe/middleware/dist/document';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export const getServerSideProps = gsspWithNonce(async (context) => {
  return { props: { message: 'Hi, from getServerSideProps' } };
});

const Home: NextPage = ({ message, nonce }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Middleware</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h2>Index page renders</h2>
        <p>{message}</p>
        <p>{nonce}</p>
      </main>
    </div>
  );
};

export default Home;
